spring:
  r2dbc:
    username: root
    password: password
    url: r2dbc:mysql://localhost:3306/test


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    cache: false

PSP:
  toss:
    secretKey: test_sk_oEjb0gm23PY6X4mwjZ9kVpGwBJn5
    url: https://api.tosspayments.com